# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        # goos: [linux, windows, darwin]
        goos: [linux]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout step
      uses: actions/checkout@v3
    - name: GCC multilib
      run: |
        sudo apt-get install gcc-multilib g++-multilib
    - name: Where clang
      run: which clang
    - name: Whereis clang
      run: whereis clang  
    # - name: Symlink GCC
    #   run: ln -s /usr/bin/clang-15 /usr/bin/clang
    # - name: Symlink GCC++
    #   run: ln -s /usr/bin/clang++-15 /usr/bin/clang++    
    - name: Build project
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: "export CGO_ENABLED=1 && export CC=aarch64-linux-gnu-gcc"
        goversion: "https://go.dev/dl/go1.21.2.linux-amd64.tar.gz"
        project_path: "."
        binary_name: "jira-sync"
        extra_files: LICENSE README.md